### ISSUE TITLE
Window opens in top-left in Linux Mint

### ISSUE THREAD

**Issue by juliencarnot** [mohd-akram/pip-vid#1]
Installed the extension in v0.4.0 from https://addons.mozilla.org/fr/firefox/addon/pip-vid/ but when I click on the PiP icon, the frame appears at top left and can't be dragged (no handle on top of frame). Can't find any ↘ button to snap to corner.
Has it been tested on different platforms? Did I miss something? Thanks!

**Comment by mohd-akram** [comment]
Just tried it, it does open in the top-left for some reason. Dragging and the snap button work though, just hover near the top of the frame.

**Comment by juliencarnot** [comment]
You're right, I had my Cinnamon dashboard on top of the screen and it took focus behind the PiP window. Putting the dashboard to the bottom makes the PiP draggable. So the extension works well and would be really useful if opening in bottom right!

**Comment by mohd-akram** [comment]
Thanks for the report, this is fixed in v0.4.1.

**Comment by juliencarnot** [comment]
Great, thanks!
