### ISSUE TITLE
No PIP icon showing up / Unable to use

### ISSUE THREAD

**Issue by MarkoPetteri** [mohd-akram/pip-vid#2]
Not sure where I should see an icon but I've search all over and cannot see. Restarted Firefox and still nothing.

I use KXStudio
Ubuntu 14.04.2 LTS
3.13.0-58-lowlatency
64bit

**Comment by mohd-akram** [comment]
You can see where the icon shows up in the screenshot on the add-on page. Which version of Firefox are you using?

**Comment by MarkoPetteri** [comment]
It started working after I forgot about installing the whole thing, so after nunerous restarts.

My Firefox is up to date.

**Comment by mohd-akram** [comment]
Strange. I'll close this ticket for now, let me know if you have any other issues.
