### ISSUE TITLE
[Feature Request] Do not show in different tabs

### ISSUE THREAD

**Issue by MaxValue** [mohd-akram/pip-vid#3]
How about an optional setting:

- The video is only visible on anything *youtube.com and does not show up in unrelated tabs.

What do you think about it?

**Comment by mohd-akram** [comment]
Not sure what you mean, are you talking about the PiP button in embedded videos?

**Comment by MaxValue** [comment]
No, when you activate the feature, the chosen video is picture-in-picture. If i switch to a different tab (regardless if it's youtube or not) it is visible.

My actual goal/wish is to have this addon behave exactly like the picture-picture feature of the official smartphone youtube app:

- You click a video -> you see it.
- You navigate to the youtube front page or a playlist or a channel -> the video gets picture-in-picture.
- You swipe the the video left or right -> it gets closed.
- You click the picture-in-picture video -> it maximizes again.
- You access another video -> the picture-in-picture video closes and you only see the new video.

**Comment by mohd-akram** [comment]
A useful feature, but somewhat out-of-scope for this add-on. Also, I need to rewrite this add-on as a WebExtension first.

**Comment by MaxValue** [comment]
Ok cool! If you rewrite it, i will take a look at it and maybe implement it myself :)
