### ISSUE TITLE
[Feature Request] Change what window clicked links open to

### ISSUE THREAD

**Issue by corwinburdick** [mohd-akram/pip-vid#5]
Would it be possible to remember which Firefox window opened the PiP window last and send any clicked links to that window? That would include clicking annotations, recommended videos, or the "Watch on youtube.com" button.

If not, would it still be possible to open those links in an already existing Firefox window rather than in a new window?

**Comment by mohd-akram** [comment]
Tried to intercept the links, but couldn't.
